[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"

[project]
name = "nasa-eo-event-platform"
version = "0.1.0"
description = "NASA Earth Observation batch and streaming data engineering platform"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka==2.15.0",
    "pyspark==4.0.2",
]

[tool.setuptools.packages.find]
where = ["src"]
